[workspace]
members = [
  "crates/mee-dev", # dev tools
  "crates/mee-transport-api", # transport api & types
  "crates/mee-transport-http", # transport - HTTP backend
  "crates/mee-did-api", # DID provider api & types
  "crates/mee-did-key", # stub did:key provider
  "crates/mee-local-store-api", # namespaced KV store api & types
  "crates/mee-local-store-mem", # KV store - in-memory backend
  "crates/mee-node-api", # node api & types
  "crates/mee-node-axum", # axum node server (for demo)
  "crates/mee-wasm", # minimal wasm facade (wasm-bindgen)
  "crates/mee-types", # shared domain types
]
resolver = "2"
