[package]
name = "mee-transport-http"
version = "0.1.0"
edition = "2021"

[dependencies]
mee-transport-api = { path = "../mee-transport-api" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
ureq = { version = "2", features = ["json"] }

