[package]
name = "mee-dev"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1"
ureq = { version = "2", features = ["json"] }
serde_json = "1"
base64 = "0.22"
