name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

jobs:
  lint-test-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just

      - name: Cache cargo/target
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: . -> target

      - name: Add wasm targets
        run: |
          rustup target add wasm32-wasip1 wasm32-unknown-unknown

      - name: Lint & type-check
        run: just check

      - name: Run tests
        run: just test

      - name: Build core WASM targets
        run: just build-core-wasm
