name: docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (BuildKit + GHA cache)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ops/Dockerfile
          push: false
          tags: local/mee-node-axum:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max

